fixed not working key_q
OSLL/dt-gui-tools_old pull request #10
Opened 2020-09-09 21:11 UTC by light5551

Также был выявлен баг и исправлен в этом же пул реквесте. Когда не было выделено объектов, но все мы нажимали на w/a/s/d выскакивало исключение, которое крашило редактор

2020-09-09 21:29 UTC, HadronCollider requested changes

2020-09-09 21:29 UTC, HadronCollider commented on packages/map_editor/mainwindow.py
> +            self.mapviewer.raw_selection = []
Значение по умолянию для `raw_selection` и `tileSelection` `[0]*4` (список из 4х нулей) - баг возникал из-за того, что raw_selection "сбрасывался" на []

2020-09-09 21:37 UTC, light5551 commented on packages/map_editor/mainwindow.py
> +            self.mapviewer.raw_selection = []
а зачем менять `tileSelection`, если /w/a/s/d/ влияет только на объекты, но никак на tiles

2020-09-09 21:41 UTC, HadronCollider commented on packages/map_editor/mainwindow.py
> +            self.mapviewer.raw_selection = []
`tileSelection` менять не нужно

2020-09-10 09:21 UTC, HadronCollider approved these changes

2020-09-10 09:21 UTC, merged