ente new arch 2
OSLL/dt-gui-tools_old pull request #138
Opened 2022-07-20 14:57 UTC by Valentina-Gol

2022-07-26 19:27 UTC, light5551 requested changes

2022-07-26 19:27 UTC, light5551 commented on packages/map_editor/layers.py
> +        return {"color": "blue", "configuration": "DB18", "id": 1}
лучше id ставить 0. Это более интуитивно понятно, что это аналог null

2022-07-26 19:27 UTC, light5551 commented on packages/map_editor/coordinatesTransformer.py
> +        return (self.size_map - y_real / self.tile_height - 1) * self.scale * (self.grid_height + 1) + 2.5 * obj_height
а что за `2.5 * obj_height`?

2022-07-26 19:27 UTC, light5551 commented on packages/map_editor/classes/layers.py
> +    def set_layer_handler(self, handler: EntityHelper) -> None:
А зачем  `EntityHelper`?

2022-07-26 19:27 UTC, light5551 commented on packages/map_editor/layers.py
> +        return super().check_config(config) and config["type"] \
А разве если в  config не будет поле type, то не возникнет ли исключения. Мб надо "type" in config

2022-07-26 19:27 UTC, light5551 commented on packages/map_editor/layers.py
> +        return super().check_config(config) and config["configuration"] \
Аналогично ^^

2022-07-26 19:27 UTC, light5551 commented on packages/map_editor/mapViewer.py
> +        self.citizens = CitizensHandler()
А зачем нам вообще это поля внутри класса? Хранить cлой для тайлов имеет смысл, потому он является первым звеном в цепочки комманд, но а другие кажется, что незачем

2022-07-26 19:27 UTC, light5551 commented on packages/map_editor/requirements.txt
> +wheel
А зачем wheel? И если нужен, то версию

2022-07-27 08:38 UTC, Valentina-Gol commented on packages/map_editor/classes/layers.py
> +    def set_layer_handler(self, handler: EntityHelper) -> None:
Используется выше, чтобы получать типы полей для слоёв

2022-07-27 09:48 UTC, Valentina-Gol commented on packages/map_editor/layers.py
> +        return super().check_config(config) and config["type"] \
Исправила

2022-07-27 09:51 UTC, Valentina-Gol commented on packages/map_editor/layers.py
> +        return super().check_config(config) and config["configuration"] \
Исправила

2022-07-27 09:51 UTC, Valentina-Gol commented on packages/map_editor/layers.py
> +        return {"color": "blue", "configuration": "DB18", "id": 1}
Исправила

2022-07-27 11:50 UTC, merged