Fixed map generation time
OSLL/dt-gui-tools_old pull request #152
Opened 2022-09-11 17:04 UTC by Valentina-Gol

2022-09-13 17:15 UTC, light5551 requested changes

2022-09-13 17:15 UTC, light5551 commented on dependencies-py3.txt
>  PyQt5
версию указать. Везде версию указать

2022-09-13 17:15 UTC, light5551 commented on packages/map_editor/forms/start_info.py
> +        self.nameDirEdit.setText("/out/map1")
А разве это будет работать например если мы запускаем локально для разработки? То есть мб сюда мы будем передавать аргумент из cli, который будем подавать

2022-09-13 17:15 UTC, light5551 commented on packages/map_editor/main.py
> +    app.setWindowIcon(QIcon("./img/icons/duckie.ico"))
А в докере это тоже корректно?

2022-09-13 17:15 UTC, light5551 commented on packages/map_editor/utils/qtWindowAPI.py
> +        return QFileDialog.getExistingDirectory(parent, f"Select a folder to {info} the map", '/out',
Аналогично

2022-09-13 18:51 UTC, Valentina-Gol commented on packages/map_editor/main.py
> +    app.setWindowIcon(QIcon("./img/icons/duckie.ico"))
Да, в докере тоже корректно

2022-09-13 21:10 UTC, Valentina-Gol commented on packages/map_editor/forms/start_info.py
> +        self.nameDirEdit.setText("/out/map1")
Добавила

2022-09-13 21:10 UTC, Valentina-Gol commented on packages/map_editor/utils/qtWindowAPI.py
> +        return QFileDialog.getExistingDirectory(parent, f"Select a folder to {info} the map", '/out',
Добавила

2022-09-13 21:10 UTC, Valentina-Gol commented on dependencies-py3.txt
>  PyQt5
Указала

2022-09-16 09:47 UTC, light5551 requested changes

2022-09-16 09:47 UTC, light5551 commented on packages/map_editor/windowDesign.py
> +        #self.maps.setTitle(_translate("MainWindow", "Map Info"))
удалить

2022-09-16 09:47 UTC, light5551 commented on launchers/editor.sh
> +#set dir
если это была пока так поставить переменную окружения, то удалить. Все равно закомментированно

2022-09-16 09:47 UTC, light5551 commented
@Valentina-Gol после исправления 2 комментов - делай мердж

2022-09-16 20:22 UTC, merged