Added dynamic layers
OSLL/dt-gui-tools_old pull request #158
Opened 2022-09-24 18:51 UTC by Valentina-Gol

2022-09-29 09:40 UTC, light5551 requested changes

2022-09-29 09:40 UTC, light5551 commented on dependencies-py3.txt
> +PyQt5
?

2022-09-29 09:40 UTC, light5551 commented on packages/map_editor/classes/Commands/AddRelativeToObj.py
> -    def execute(self, dm: Map, layer: MapLayer, layer_name: str, *args,
А почему мы убираем объект Map в этом методе.  Почему уверены, что он нам никогда не пригодится

2022-09-29 09:40 UTC, light5551 commented on packages/map_editor/classes/layers.py
> +        self._layer_name = kwargs["layer_name"]
Константы вместо строк

2022-09-29 09:40 UTC, light5551 commented on packages/map_editor/forms/edit_object.py
> +                    val = eval(self.info[key].text())
Пожалуй, сложное место. Как это правильно читать?

2022-09-29 09:40 UTC, light5551 commented on packages/map_editor/mapAPI.py
> +                check_list = ["tiles.yaml", "frames.yaml", "tile_maps.yaml"]
Для чего чек-лист? И почему именно такой?

2022-09-29 09:40 UTC, light5551 commented on packages/map_editor/mapViewer.py
> +        module = import_module("layers")
Добавь комменты здесь

2022-09-29 17:30 UTC, Valentina-Gol commented on packages/map_editor/classes/Commands/AddRelativeToObj.py
> -    def execute(self, dm: Map, layer: MapLayer, layer_name: str, *args,
Т.к. команды работают с отдельными слоями, то аргумента layer должно хватить для того, чтобы с ними работать. Если dm всё таки понадобится, мы сможет передать его в kwargs

2022-09-29 17:32 UTC, Valentina-Gol commented on packages/map_editor/forms/edit_object.py
> +                    val = eval(self.info[key].text())
Получаем self.info[key] по key, потом получаем его текстовое представление через .text(). Потом приводим к типу, который должен быть у этого поля. Тип был сохранен в (self.info["types"][key]). И всё это присваиваем в конфиг self.info_send["new_config"][key]

2022-09-29 17:34 UTC, Valentina-Gol commented on packages/map_editor/mapAPI.py
> +                check_list = ["tiles.yaml", "frames.yaml", "tile_maps.yaml"]
Это ключевые слои, без которых карта не будет корректно работать. Если одного из файлов не будет в папке, редактор упадёт и это никак не пофиксить

2022-09-29 17:35 UTC, Valentina-Gol commented on dependencies-py3.txt
> +PyQt5
Смержилось автоматически, удалю

2022-09-29 17:40 UTC, Valentina-Gol commented on packages/map_editor/classes/layers.py
> +        self._layer_name = kwargs["layer_name"]
Исправлено

2022-09-29 17:40 UTC, Valentina-Gol commented on packages/map_editor/mapViewer.py
> +        module = import_module("layers")
Добавила

2022-10-01 15:10 UTC, light5551 commented on packages/map_editor/mapAPI.py
> +                check_list = ["tiles.yaml", "frames.yaml", "tile_maps.yaml"]
мб тогда это вынести в отдельную переменную, в некий конфиг  как обязательные слои

2022-10-01 15:11 UTC, light5551 commented on packages/map_editor/forms/edit_object.py
> +                    val = eval(self.info[key].text())
Разве eval - это привидение типов?

2022-10-03 13:28 UTC, Valentina-Gol commented on packages/map_editor/forms/edit_object.py
> +                    val = eval(self.info[key].text())
Это мы парсим json объект

2022-10-03 13:34 UTC, Valentina-Gol commented on packages/map_editor/mapAPI.py
> +                check_list = ["tiles.yaml", "frames.yaml", "tile_maps.yaml"]
Вынесла

2022-10-19 15:26 UTC, merged