New features
OSLL/dt-gui-tools_old pull request #178
Opened 2022-10-19 16:11 UTC by Valentina-Gol

2022-10-23 16:15 UTC, light5551 requested changes

2022-10-23 16:15 UTC, light5551 commented on packages/map_editor/forms/edit_object.py
> +        self.float_accuracy = 5
accuracy - неудачно слово. Это слишком буквальный перевод с русского на английский. мб  лучше float_formatting

2022-10-23 16:15 UTC, light5551 commented on packages/map_editor/forms/edit_object.py
> +            if self.layer_name == "tiles" and (key == "i" or key == "j"):
Константы вместо строк

2022-11-01 09:39 UTC, Valentina-Gol commented on packages/map_editor/forms/edit_object.py
> +        self.float_accuracy = 5
Заменила

2022-11-01 09:39 UTC, Valentina-Gol commented on packages/map_editor/forms/edit_object.py
> +            if self.layer_name == "tiles" and (key == "i" or key == "j"):
Заменила

2022-12-02 15:10 UTC, merged