validation field
OSLL/dt-gui-tools_old pull request #33
Opened 2020-09-16 21:29 UTC by light5551

#24

2020-09-16 21:46 UTC, HadronCollider requested changes
Стоит добавить подобное поведение для окна редактирования атрибутов объекта, иначе сейчас редактирование не имеет ничего общего с созданием (как по значениям, так и по валидации)

2020-09-16 21:46 UTC, HadronCollider commented on packages/map_editor/forms/new_tag_object.py
> +        tag_id = int(self.lineEdit.text())
https://stackoverflow.com/questions/15829782/how-to-restrict-user-input-in-qlineedit-in-pyqt

2020-09-16 21:46 UTC, HadronCollider commented on packages/map_editor/forms/new_tag_object.py
> +        hbox.addWidget(self.combo_id)
Вместо двух элементов (список + поле ввода) желательно использовать их объединение - https://evileg.com/en/post/235/

2020-09-16 22:53 UTC, HadronCollider requested changes
Касательно https://github.com/OSLL/dt-gui-tools/blob/24_issue/packages/map_editor/img/apriltags/apriltag_300.png, кажется, говорилось о широкой рамке изображения (~10-20%), т.е. приближенной к реальности:
![image](https://user-images.githubusercontent.com/21632402/93400197-e9806280-f887-11ea-8198-99d1cf3ce3b6.png)

2020-09-17 15:30 UTC, light5551 commented on packages/map_editor/forms/new_tag_object.py
> +        hbox.addWidget(self.combo_id)
это не совсем то, что ты описал. Там только авподстановка

2020-09-17 15:57 UTC, HadronCollider commented on packages/map_editor/forms/new_tag_object.py
> +        hbox.addWidget(self.combo_id)
Да, действительно.
Всё несколько проще: https://www.geeksforgeeks.org/pyqt5-setting-line-edit-to-the-combobox/

2020-09-17 17:59 UTC, HadronCollider commented
> добавить подобное поведение для окна редактирования атрибутов объекта, иначе сейчас редактирование не имеет ничего общего с созданием (как по значениям, так и по валидации)

2020-09-17 17:59 UTC, HadronCollider requested changes
> добавить подобное поведение для окна редактирования атрибутов объекта, иначе сейчас редактирование не имеет ничего общего с созданием (как по значениям, так и по валидации)

Сюда же можно добавить надоработку по https://github.com/OSLL/dt-gui-tools/issues/12 с id/type для знаков

2020-09-17 20:52 UTC, HadronCollider requested changes
Редактирую атрибуты дорожного знака, сохраняю, получаю ошибку:
```
Traceback (most recent call last):
  File "D:\Git\dt-gui-tools\packages\map_editor\mainwindow.py", line 625, in accept
    tag_type = edit_obj['tag_type'].text()
KeyError: 'tag_type'
```
А так же
```
Traceback (most recent call last):
  File "D:\Git\dt-gui-tools\packages\map_editor\mainwindow.py", line 624, in accept
    tag_id = int(edit_obj['tag_id'].text())
KeyError: 'tag_id'
```
для городских объектов/сторожевых башен = объектов, у которых нет ни `tag_id`, ни `tag_type`

2020-09-17 21:19 UTC, HadronCollider requested changes

2020-09-17 21:19 UTC, HadronCollider commented on packages/map_editor/mainwindow.py
> +                tag_type = edit_obj['tag_type'].text()
Дорожные знаки не имеют `tag_type`: при их редактировании возникает исключение и в итоге проверка id не осуществляется

2020-09-18 11:43 UTC, HadronCollider requested changes

2020-09-18 11:43 UTC, HadronCollider commented on packages/map_editor/mainwindow.py
> +                    return
> Если в `edit_obj` есть `tag_id`, но нет `tag_type` - это должен быть дорожный знак, валидацию `tag_id` для них можно проводить с помощью https://github.com/OSLL/dt-gui-tools/blob/659f8b6118918cf1b48071c8c3a6faa78b98e184/packages/map_editor/tag_config.py#L7
`TRAFFIC_SIGN_TYPES` содержит структуру 
>```
>{
>    <traffic_sign_type>: [ids]
>	# traffic_sign_type == kind для знаков 
>}
>```
Сейчас всё ещё возможно создание, например, знака `stop` с `tag_id=11111111` - валидация tag_id для знака по типу знака не осуществляется

2020-09-18 12:09 UTC, HadronCollider approved these changes

2020-09-18 12:12 UTC, merged