150 153 issue
OSLL/dt-gui-tools_old pull request #9
Opened 2020-09-09 21:04 UTC by light5551

https://github.com/moevm/mse_visual_map_editor_for_duckietown/issues/150
https://github.com/moevm/mse_visual_map_editor_for_duckietown/issues/153

2020-09-09 21:15 UTC, HadronCollider requested changes
- Проблема с областью срабатывания ПКМ (отмечена)
- "Центром" изображения является центр выделенной области, а не реальный центр изображения
![image](https://user-images.githubusercontent.com/21632402/92655638-68aaef00-f2fa-11ea-8076-dd5b01abb7e8.png)

2020-09-09 21:22 UTC, light5551 commented
> * Проблема с областью срабатывания ПКМ (отмечена)
> * "Центром" изображения является центр выделенной области, а не реальный центр изображения
>   ![image](https://user-images.githubusercontent.com/21632402/92655638-68aaef00-f2fa-11ea-8076-dd5b01abb7e8.png)

такой баг происходит когда объект вне поля. Я думаю в будущем надо будет поменять изначальную позицию

2020-09-09 21:38 UTC, HadronCollider commented
Определяемые границы/размеры изображения (т.е. и зависящие от них выделение центра/срабатываение пкм) всё же несколько непредсказуемы и некорректны:
![image](https://user-images.githubusercontent.com/21632402/92657533-abba9180-f2fd-11ea-94ae-369dc453bdc6.png)

Проблема с объектами за пределами карты может быть связано с отрицательными координатами - стоит это проверить

2020-09-11 07:06 UTC, HadronCollider approved these changes

2020-09-11 07:33 UTC, merged